package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	defaultRulesGoVersion        = "0.59.0"
	defaultRulesGoRemote         = "https://github.com/DataDog/rules_test_optimization.git"
	defaultRulesGoCommit         = "16712cc851915317659b932471dcb68af48dd5bb"
	defaultRulesGoStripPrefix    = "third_party/rules_go_orchestrion"
	defaultOrchestrionVersion    = "v1.5.0"
	defaultSyncRepoName          = "test_optimization_data"
	defaultUploaderTargetName    = "dd_upload_payloads"
	managedBlockStart            = "# BEGIN Datadog Go Orchestrion bootstrap"
	managedBlockEnd              = "# END Datadog Go Orchestrion bootstrap"
	guidedBlockStart             = "# BEGIN Datadog Go Guided Setup"
	guidedBlockEnd               = "# END Datadog Go Guided Setup"
	uploaderBlockStart           = "# BEGIN Datadog Go Uploader"
	uploaderBlockEnd             = "# END Datadog Go Uploader"
	wrapperBlockStart            = "# BEGIN Datadog Go Wrapper"
	wrapperBlockEnd              = "# END Datadog Go Wrapper"
	defaultStarterOrchestrionYML = `---
# yaml-language-server: $schema=https://datadoghq.dev/orchestrion/schema.json
meta:
  name: datadog/go-bootstrap
  description: Datadog starter configuration for Orchestrion.

aspects: []
`
	sharedOrchestrionCacheDirName = "datadog-orchestrion-go-cache"
	toolsBuildDir                 = "tools/build"
	wrapperFileName               = "dd_go_test.bzl"
)

type config struct {
	workspaceDir       string
	moduleFile         string
	goModuleDir        string
	force              bool
	guided             bool
	service            string
	runtimeVersion     string
	syncRepoName       string
	uploaderTargetName string
	orchestrionVersion string
	rulesGoRemote      string
	rulesGoCommit      string
}

func main() {
	cfg := parseFlags()
	if err := run(cfg); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func parseFlags() config {
	workspaceDefault := os.Getenv("BUILD_WORKSPACE_DIRECTORY")
	if workspaceDefault == "" {
		cwd, _ := os.Getwd()
		workspaceDefault = cwd
	}

	cfg := config{}
	flag.StringVar(&cfg.workspaceDir, "workspace", workspaceDefault, "Workspace root to update")
	flag.StringVar(&cfg.goModuleDir, "go-module-dir", "", "Go module directory to pin for Orchestrion (defaults to workspace root)")
	flag.BoolVar(&cfg.force, "force", false, "Allow overwriting Datadog-managed bootstrap files")
	flag.BoolVar(&cfg.guided, "guided", false, "Generate Datadog-managed single-service Go onboarding files")
	flag.StringVar(&cfg.service, "service", "", "Datadog service name for guided single-service Go setup")
	flag.StringVar(&cfg.runtimeVersion, "runtime-version", "", "Go runtime version for guided single-service Go setup")
	flag.StringVar(&cfg.syncRepoName, "sync-repo-name", defaultSyncRepoName, "Repository name generated by guided single-service Go setup")
	flag.StringVar(&cfg.uploaderTargetName, "uploader-target-name", defaultUploaderTargetName, "Root uploader target name generated by guided single-service Go setup")
	flag.StringVar(&cfg.orchestrionVersion, "orchestrion-version", defaultOrchestrionVersion, "Orchestrion version to configure")
	flag.StringVar(&cfg.rulesGoRemote, "rules-go-remote", defaultRulesGoRemote, "rules_go fork remote used for Orchestrion support")
	flag.StringVar(&cfg.rulesGoCommit, "rules-go-commit", defaultRulesGoCommit, "rules_go fork commit used for Orchestrion support")
	flag.Parse()
	return cfg
}

func run(cfg config) error {
	if cfg.workspaceDir == "" {
		return errors.New("workspace directory is required")
	}
	workspaceDir, err := filepath.Abs(cfg.workspaceDir)
	if err != nil {
		return fmt.Errorf("resolve workspace: %w", err)
	}
	cfg.workspaceDir = workspaceDir
	if cfg.goModuleDir == "" {
		cfg.goModuleDir = workspaceDir
	} else if !filepath.IsAbs(cfg.goModuleDir) {
		cfg.goModuleDir = filepath.Join(workspaceDir, cfg.goModuleDir)
	}
	cfg.moduleFile = filepath.Join(workspaceDir, "MODULE.bazel")

	if cfg.guided {
		if strings.TrimSpace(cfg.service) == "" {
			return errors.New("--guided requires --service")
		}
		if strings.TrimSpace(cfg.runtimeVersion) == "" {
			return errors.New("--guided requires --runtime-version")
		}
		if strings.TrimSpace(cfg.syncRepoName) == "" {
			return errors.New("--guided requires a non-empty --sync-repo-name")
		}
		if strings.TrimSpace(cfg.uploaderTargetName) == "" {
			return errors.New("--guided requires a non-empty --uploader-target-name")
		}
	}

	if err := ensureFileExists(cfg.moduleFile, "MODULE.bazel"); err != nil {
		return err
	}
	if err := ensureFileExists(filepath.Join(cfg.goModuleDir, "go.mod"), "go.mod"); err != nil {
		return err
	}

	if err := patchModuleFile(cfg); err != nil {
		return err
	}
	if cfg.guided {
		if err := ensureGuidedWorkspaceFiles(cfg); err != nil {
			return err
		}
	}
	if err := runOrchestrionPin(cfg); err != nil {
		return err
	}
	if err := ensureCIVisibilityOrchestrionImport(cfg); err != nil {
		return err
	}
	if err := warmOrchestrionModuleCache(cfg); err != nil {
		return err
	}
	if err := writeStarterOrchestrionYML(cfg); err != nil {
		return err
	}

	fmt.Printf("Updated %s and pinned Orchestrion in %s\n", cfg.moduleFile, cfg.goModuleDir)
	return nil
}

func ensureFileExists(path, label string) error {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("%s not found at %s", label, path)
		}
		return fmt.Errorf("stat %s: %w", path, err)
	}
	if info.IsDir() {
		return fmt.Errorf("%s path is a directory: %s", label, path)
	}
	return nil
}

func patchModuleFile(cfg config) error {
	content, err := os.ReadFile(cfg.moduleFile)
	if err != nil {
		return fmt.Errorf("read MODULE.bazel: %w", err)
	}
	text := string(content)

	if cfg.guided {
		if err := validateGuidedPrerequisites(text); err != nil {
			return err
		}
	}

	if !strings.Contains(text, `bazel_dep(name = "rules_go"`) && !strings.Contains(text, `bazel_dep(name="rules_go"`) {
		snippet := fmt.Sprintf(`bazel_dep(name = "rules_go", version = "%s")%s`, defaultRulesGoVersion, "\n")
		text, err = insertAfterModuleDecl(text, snippet)
		if err != nil {
			return err
		}
	}

	if cfg.rulesGoRemote == defaultRulesGoRemote && cfg.rulesGoCommit == defaultRulesGoCommit {
		if remote, commit := inferDatadogRepoOverride(text); remote != "" && commit != "" {
			cfg.rulesGoRemote = remote
			cfg.rulesGoCommit = commit
		}
	}

	if !strings.Contains(text, managedBlockStart) && strings.Contains(text, `module_name = "rules_go"`) && !rulesGoOverrideCompatible(text, cfg) {
		return errors.New("MODULE.bazel already contains an incompatible rules_go git_override; update it manually before running the Datadog bootstrap")
	}

	managedBlock := managedModuleBlock(cfg)

	text, err = replaceManagedSection(text, managedBlockStart, managedBlockEnd, managedBlock)
	if err != nil {
		return err
	}

	if cfg.guided {
		addGuidedBlock, err := shouldAddGuidedBlock(text, cfg)
		if err != nil {
			return err
		}
		if addGuidedBlock {
			text, err = replaceManagedSection(text, guidedBlockStart, guidedBlockEnd, managedGuidedModuleBlock(cfg))
			if err != nil {
				return err
			}
		}
	}

	if err := os.WriteFile(cfg.moduleFile, []byte(text), 0o644); err != nil {
		return fmt.Errorf("write MODULE.bazel: %w", err)
	}
	return nil
}

func managedModuleBlock(cfg config) string {
	return fmt.Sprintf(`%s
git_override(
    module_name = "rules_go",
    remote = "%s",
    commit = "%s",
    strip_prefix = "%s",
)

orchestrion = use_extension("@rules_go//go:extensions.bzl", "orchestrion")
orchestrion.from_source(version = "%s")
use_repo(orchestrion, "rules_go_orchestrion_tool")
%s
`, managedBlockStart, cfg.rulesGoRemote, cfg.rulesGoCommit, defaultRulesGoStripPrefix, cfg.orchestrionVersion, managedBlockEnd)
}

func managedGuidedModuleBlock(cfg config) string {
	return fmt.Sprintf(`%s
datadog_go_topt = use_extension(
    "@datadog-rules-test-optimization-go//:topt_go_extension.bzl",
    "test_optimization_go_extension",
)

datadog_go_topt.test_optimization_go(
    name = "%s",
    service = "%s",
    runtime_version = "%s",
)

use_repo(datadog_go_topt, "%s")
%s
`, guidedBlockStart, cfg.syncRepoName, cfg.service, cfg.runtimeVersion, cfg.syncRepoName, guidedBlockEnd)
}

func insertAfterModuleDecl(content, snippet string) (string, error) {
	start := strings.Index(content, "module(")
	if start < 0 {
		return "", errors.New("MODULE.bazel does not contain a module(...) declaration")
	}
	depth := 0
	for idx, r := range content[start:] {
		switch r {
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 {
				insertAt := start + idx + 1
				return content[:insertAt] + "\n\n" + snippet + content[insertAt:], nil
			}
		}
	}
	return "", errors.New("failed to locate the end of module(...) in MODULE.bazel")
}

func replaceManagedSection(content, startMarker, endMarker, block string) (string, error) {
	start := strings.Index(content, startMarker)
	end := strings.Index(content, endMarker)
	switch {
	case start >= 0 && end >= 0 && end > start:
		end += len(endMarker)
		return content[:start] + block + content[end:], nil
	case start >= 0 || end >= 0:
		return "", fmt.Errorf("existing Datadog managed block is malformed: %s / %s", startMarker, endMarker)
	}

	var buf bytes.Buffer
	buf.WriteString(content)
	if !strings.HasSuffix(content, "\n") {
		buf.WriteString("\n")
	}
	buf.WriteString("\n")
	buf.WriteString(block)
	return buf.String(), nil
}

func inferDatadogRepoOverride(content string) (string, string) {
	overridePattern := regexp.MustCompile(`(?s)git_override\(\s*module_name\s*=\s*"([^"]+)"(.*?)\n\)`)
	remotePattern := regexp.MustCompile(`remote\s*=\s*"([^"]+)"`)
	commitPattern := regexp.MustCompile(`commit\s*=\s*"([^"]+)"`)

	for _, match := range overridePattern.FindAllStringSubmatch(content, -1) {
		moduleName := match[1]
		if moduleName != "datadog-rules-test-optimization" && moduleName != "datadog-rules-test-optimization-go" {
			continue
		}
		body := match[2]
		remoteMatch := remotePattern.FindStringSubmatch(body)
		commitMatch := commitPattern.FindStringSubmatch(body)
		if len(remoteMatch) < 2 || len(commitMatch) < 2 {
			continue
		}
		return remoteMatch[1], commitMatch[1]
	}
	return "", ""
}

type goExtensionCall struct {
	name           string
	service        string
	runtimeVersion string
	hasServices    bool
}

func validateGuidedPrerequisites(content string) error {
	if !hasModuleReference(content, "datadog-rules-test-optimization") {
		return errors.New("guided bootstrap requires the Datadog core module wiring in MODULE.bazel; add the datadog-rules-test-optimization dependency/override first")
	}
	if !hasModuleReference(content, "datadog-rules-test-optimization-go") {
		return errors.New("guided bootstrap requires the Datadog Go companion wiring in MODULE.bazel; add the datadog-rules-test-optimization-go dependency/override first")
	}
	return nil
}

func hasModuleReference(content, moduleName string) bool {
	patterns := []string{
		fmt.Sprintf(`bazel_dep(name = "%s"`, moduleName),
		fmt.Sprintf(`bazel_dep(name="%s"`, moduleName),
		fmt.Sprintf(`module_name = "%s"`, moduleName),
		fmt.Sprintf(`module_name="%s"`, moduleName),
	}
	for _, pattern := range patterns {
		if strings.Contains(content, pattern) {
			return true
		}
	}
	return false
}

func shouldAddGuidedBlock(content string, cfg config) (bool, error) {
	hasManagedGuidedBlock := strings.Contains(content, guidedBlockStart) || strings.Contains(content, guidedBlockEnd)
	scanContent := content
	if stripped, ok := stripManagedSectionIfPresent(content, guidedBlockStart, guidedBlockEnd); ok {
		scanContent = stripped
	}

	if strings.Contains(scanContent, `"test_optimization_sync_extension"`) {
		return false, errors.New("guided bootstrap only supports fresh single-service Go workspaces; found existing test_optimization_sync_extension setup")
	}
	if strings.Contains(scanContent, `"test_optimization_multi_sync_extension"`) {
		return false, errors.New("guided bootstrap only supports fresh single-service Go workspaces; found existing test_optimization_multi_sync_extension setup")
	}

	if !strings.Contains(scanContent, `"test_optimization_go_extension"`) && !strings.Contains(scanContent, `.test_optimization_go(`) {
		return true, nil
	}

	calls := extractGoExtensionCalls(scanContent)
	if len(calls) == 0 {
		return false, errors.New("guided bootstrap found existing test_optimization_go_extension wiring but could not validate it; use the manual Go setup path instead")
	}
	if len(calls) > 1 {
		return false, errors.New("guided bootstrap only supports fresh single-service Go workspaces; found multiple test_optimization_go(...) tags")
	}

	call := calls[0]
	if call.hasServices {
		return false, errors.New("guided bootstrap only supports fresh single-service Go workspaces; found services = [...] in test_optimization_go(...)")
	}
	if call.name != cfg.syncRepoName || call.service != cfg.service || call.runtimeVersion != cfg.runtimeVersion {
		return false, fmt.Errorf("guided bootstrap found conflicting test_optimization_go(...) wiring (name=%q service=%q runtime_version=%q); use the manual Go setup path instead", call.name, call.service, call.runtimeVersion)
	}
	if !moduleUsesRepo(scanContent, cfg.syncRepoName) {
		return false, fmt.Errorf("guided bootstrap found matching test_optimization_go(...) wiring but missing use_repo(..., %q); use the manual Go setup path instead", cfg.syncRepoName)
	}
	if hasManagedGuidedBlock {
		return false, errors.New("guided bootstrap found duplicate single-service Go sync wiring outside the Datadog-managed block; use the manual Go setup path instead")
	}
	return false, nil
}

func stripManagedSectionIfPresent(content, startMarker, endMarker string) (string, bool) {
	start := strings.Index(content, startMarker)
	end := strings.Index(content, endMarker)
	if start < 0 || end < 0 || end <= start {
		return content, false
	}
	end += len(endMarker)
	return content[:start] + content[end:], true
}

func extractGoExtensionCalls(content string) []goExtensionCall {
	callPattern := regexp.MustCompile(`(?s)[A-Za-z_][A-Za-z0-9_]*\.test_optimization_go\((.*?)\n\)`)
	namePattern := regexp.MustCompile(`(?m)^\s*name\s*=\s*"([^"]+)"`)
	servicePattern := regexp.MustCompile(`(?m)^\s*service\s*=\s*"([^"]+)"`)
	runtimeVersionPattern := regexp.MustCompile(`(?m)^\s*runtime_version\s*=\s*"([^"]+)"`)
	servicesPattern := regexp.MustCompile(`(?m)^\s*services\s*=`)

	matches := callPattern.FindAllStringSubmatch(content, -1)
	calls := make([]goExtensionCall, 0, len(matches))
	for _, match := range matches {
		body := match[1]
		call := goExtensionCall{
			hasServices: servicesPattern.MatchString(body),
		}
		if nameMatch := namePattern.FindStringSubmatch(body); len(nameMatch) == 2 {
			call.name = nameMatch[1]
		}
		if serviceMatch := servicePattern.FindStringSubmatch(body); len(serviceMatch) == 2 {
			call.service = serviceMatch[1]
		}
		if runtimeVersionMatch := runtimeVersionPattern.FindStringSubmatch(body); len(runtimeVersionMatch) == 2 {
			call.runtimeVersion = runtimeVersionMatch[1]
		}
		calls = append(calls, call)
	}
	return calls
}

func moduleUsesRepo(content, repoName string) bool {
	pattern := regexp.MustCompile(`(?s)use_repo\((.*?)\)`)
	for _, match := range pattern.FindAllStringSubmatch(content, -1) {
		if strings.Contains(match[1], fmt.Sprintf("%q", repoName)) {
			return true
		}
	}
	return false
}

func rulesGoOverrideCompatible(content string, cfg config) bool {
	overridePattern := regexp.MustCompile(`(?s)git_override\(\s*module_name\s*=\s*"rules_go"(.*?)\n\)`)
	remotePattern := regexp.MustCompile(`remote\s*=\s*"([^"]+)"`)
	commitPattern := regexp.MustCompile(`commit\s*=\s*"([^"]+)"`)
	stripPrefixPattern := regexp.MustCompile(`strip_prefix\s*=\s*"([^"]+)"`)

	match := overridePattern.FindStringSubmatch(content)
	if len(match) < 2 {
		return false
	}
	body := match[1]
	remoteMatch := remotePattern.FindStringSubmatch(body)
	commitMatch := commitPattern.FindStringSubmatch(body)
	stripPrefixMatch := stripPrefixPattern.FindStringSubmatch(body)
	if len(remoteMatch) < 2 || len(commitMatch) < 2 || len(stripPrefixMatch) < 2 {
		return false
	}
	return remoteMatch[1] == cfg.rulesGoRemote && commitMatch[1] == cfg.rulesGoCommit && stripPrefixMatch[1] == defaultRulesGoStripPrefix
}

func ensureGuidedWorkspaceFiles(cfg config) error {
	if err := ensureGuidedRootBuild(cfg); err != nil {
		return err
	}
	if err := ensureGuidedWrapper(cfg); err != nil {
		return err
	}
	return nil
}

func ensureGuidedRootBuild(cfg config) error {
	buildPath, err := selectPackageFile(cfg.workspaceDir)
	if err != nil {
		return err
	}
	content, err := os.ReadFile(buildPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", buildPath, err)
	}
	text := string(content)

	if !strings.Contains(text, uploaderBlockStart) && hasNamedTarget(text, cfg.uploaderTargetName) {
		if !cfg.force {
			return fmt.Errorf("%s already contains an unmanaged target named %q; rerun with --force or use the manual Go setup path", filepath.Base(buildPath), cfg.uploaderTargetName)
		}
		text, err = removeNamedTarget(text, cfg.uploaderTargetName)
		if err != nil {
			return err
		}
	}

	text, err = ensureLoadStatement(text, `load("@datadog-rules-test-optimization//tools/core:test_optimization_uploader.bzl", "dd_payload_uploader")`)
	if err != nil {
		return err
	}

	block := fmt.Sprintf(`%s
dd_payload_uploader(
    name = "%s",
    data = ["@%s//:test_optimization_context"],
)
%s
`, uploaderBlockStart, cfg.uploaderTargetName, cfg.syncRepoName, uploaderBlockEnd)
	text, err = replaceManagedSection(text, uploaderBlockStart, uploaderBlockEnd, block)
	if err != nil {
		return err
	}

	if err := os.WriteFile(buildPath, []byte(text), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", buildPath, err)
	}
	return nil
}

func ensureGuidedWrapper(cfg config) error {
	wrapperDir := filepath.Join(cfg.workspaceDir, toolsBuildDir)
	if err := os.MkdirAll(wrapperDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", wrapperDir, err)
	}
	packagePath, err := selectPackageFile(wrapperDir)
	if err != nil {
		return err
	}
	if _, err := os.Stat(packagePath); os.IsNotExist(err) {
		if err := os.WriteFile(packagePath, []byte("# Package marker for workspace-local test wrapper macros.\n"), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", packagePath, err)
		}
	} else if err != nil {
		return fmt.Errorf("stat %s: %w", packagePath, err)
	}

	wrapperPath := filepath.Join(wrapperDir, wrapperFileName)
	existing, err := os.ReadFile(wrapperPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", wrapperPath, err)
	}
	if len(existing) > 0 && (!strings.Contains(string(existing), wrapperBlockStart) || !strings.Contains(string(existing), wrapperBlockEnd)) && !cfg.force {
		return fmt.Errorf("%s already exists and is not Datadog-managed; rerun with --force or use the manual Go setup path", wrapperPath)
	}

	wrapperContent := fmt.Sprintf(`"""Datadog-managed workspace-local wrapper for Go test optimization."""

%s
load("@datadog-rules-test-optimization-go//:topt_go_test.bzl", "dd_topt_go_test")
load("@%s//:export.bzl", "topt_data")

def dd_go_test(name, **kwargs):
    dd_topt_go_test(
        name = name,
        topt_data = topt_data,
        **kwargs
    )
%s
`, wrapperBlockStart, cfg.syncRepoName, wrapperBlockEnd)
	if err := os.WriteFile(wrapperPath, []byte(wrapperContent), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", wrapperPath, err)
	}
	return nil
}

func selectPackageFile(dir string) (string, error) {
	buildBazel := filepath.Join(dir, "BUILD.bazel")
	if _, err := os.Stat(buildBazel); err == nil {
		return buildBazel, nil
	} else if err != nil && !os.IsNotExist(err) {
		return "", fmt.Errorf("stat %s: %w", buildBazel, err)
	}

	build := filepath.Join(dir, "BUILD")
	if _, err := os.Stat(build); err == nil {
		return build, nil
	} else if err != nil && !os.IsNotExist(err) {
		return "", fmt.Errorf("stat %s: %w", build, err)
	}
	return buildBazel, nil
}

func ensureLoadStatement(content, loadStatement string) (string, error) {
	if strings.Contains(content, loadStatement) {
		return content, nil
	}

	lines := splitLinesPreserveNewline(content)
	insertAt := 0
	inLoad := false
	loadDepth := 0

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch {
		case inLoad:
			insertAt += len(line)
			loadDepth += strings.Count(line, "(")
			loadDepth -= strings.Count(line, ")")
			if loadDepth <= 0 {
				inLoad = false
			}
		case trimmed == "" || strings.HasPrefix(trimmed, "#"):
			insertAt += len(line)
		case strings.HasPrefix(trimmed, "load("):
			inLoad = true
			loadDepth = strings.Count(line, "(") - strings.Count(line, ")")
			insertAt += len(line)
			if loadDepth <= 0 {
				inLoad = false
			}
		default:
			goto insert
		}
	}

insert:
	var buf bytes.Buffer
	buf.WriteString(content[:insertAt])
	buf.WriteString(loadStatement)
	buf.WriteString("\n")
	buf.WriteString(content[insertAt:])
	return buf.String(), nil
}

func splitLinesPreserveNewline(content string) []string {
	if content == "" {
		return nil
	}
	lines := strings.SplitAfter(content, "\n")
	if !strings.HasSuffix(content, "\n") {
		return lines
	}
	if len(lines) > 0 && lines[len(lines)-1] == "" {
		return lines[:len(lines)-1]
	}
	return lines
}

type callBlock struct {
	function string
	text     string
	start    int
	end      int
}

func topLevelCallBlocks(content string) []callBlock {
	lines := splitLinesPreserveNewline(content)
	startPattern := regexp.MustCompile(`^\s*([A-Za-z_][A-Za-z0-9_]*)\(`)
	offset := 0
	blocks := []callBlock{}

	for i := 0; i < len(lines); i++ {
		line := lines[i]
		match := startPattern.FindStringSubmatch(line)
		if match == nil {
			offset += len(line)
			continue
		}
		start := offset
		depth := strings.Count(line, "(") - strings.Count(line, ")")
		offset += len(line)
		j := i
		for depth > 0 && j+1 < len(lines) {
			j++
			line = lines[j]
			depth += strings.Count(line, "(")
			depth -= strings.Count(line, ")")
			offset += len(line)
		}
		blocks = append(blocks, callBlock{
			function: match[1],
			text:     content[start:offset],
			start:    start,
			end:      offset,
		})
		i = j
	}
	return blocks
}

func hasNamedTarget(content, targetName string) bool {
	for _, block := range topLevelCallBlocks(content) {
		if block.function == "load" {
			continue
		}
		if extractBlockName(block.text) == targetName {
			return true
		}
	}
	return false
}

func removeNamedTarget(content, targetName string) (string, error) {
	blocks := topLevelCallBlocks(content)
	var removed bool
	var out strings.Builder
	last := 0
	for _, block := range blocks {
		if block.function == "load" {
			continue
		}
		if extractBlockName(block.text) != targetName {
			continue
		}
		out.WriteString(content[last:block.start])
		last = block.end
		removed = true
	}
	if !removed {
		return content, nil
	}
	out.WriteString(content[last:])
	return out.String(), nil
}

func extractBlockName(block string) string {
	pattern := regexp.MustCompile(`(?m)^\s*name\s*=\s*"([^"]+)"`)
	match := pattern.FindStringSubmatch(block)
	if len(match) != 2 {
		return ""
	}
	return match[1]
}

func runOrchestrionPin(cfg config) error {
	cmd := exec.Command("go", "run", "github.com/DataDog/orchestrion@"+cfg.orchestrionVersion, "pin")
	cmd.Dir = cfg.goModuleDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = orchestrionBootstrapEnv()
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("run orchestrion pin in %s: %w", cfg.goModuleDir, err)
	}
	return nil
}

func ensureCIVisibilityOrchestrionImport(cfg config) error {
	path := filepath.Join(cfg.goModuleDir, "orchestrion.tool.go")
	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read orchestrion.tool.go: %w", err)
	}
	text := string(content)

	const (
		legacyCIVisibilityImport     = `_ "gopkg.in/DataDog/dd-trace-go.v1/civisibility" // integration`
		legacyCIVisibilityImportBare = `_ "gopkg.in/DataDog/dd-trace-go.v1/civisibility"`
		v2OrchestrionImport          = `_ "github.com/DataDog/dd-trace-go/v2/orchestrion" // integration`
		v2AllImport                  = `_ "github.com/DataDog/dd-trace-go/orchestrion/all/v2" // integration`
		v2AllImportBare              = `_ "github.com/DataDog/dd-trace-go/orchestrion/all/v2"`
		v2GotestingImport            = `_ "github.com/DataDog/dd-trace-go/v2/internal/civisibility/integrations/gotesting" // integration`
		v2GotestingImportBare        = `_ "github.com/DataDog/dd-trace-go/v2/internal/civisibility/integrations/gotesting"`
	)

	updated := strings.ReplaceAll(text, legacyCIVisibilityImport+"\n", "")
	updated = strings.ReplaceAll(updated, legacyCIVisibilityImport, "")
	updated = strings.ReplaceAll(updated, legacyCIVisibilityImportBare+"\n", "")
	updated = strings.ReplaceAll(updated, legacyCIVisibilityImportBare, "")
	updated = strings.ReplaceAll(updated, v2AllImport+"\n", "")
	updated = strings.ReplaceAll(updated, v2AllImport, "")
	updated = strings.ReplaceAll(updated, v2AllImportBare+"\n", "")
	updated = strings.ReplaceAll(updated, v2AllImportBare, "")
	updated = strings.ReplaceAll(updated, v2GotestingImport+"\n", "")
	updated = strings.ReplaceAll(updated, v2GotestingImport, "")
	updated = strings.ReplaceAll(updated, v2GotestingImportBare+"\n", "")
	updated = strings.ReplaceAll(updated, v2GotestingImportBare, "")
	updated = strings.ReplaceAll(updated, "\n\n\n", "\n\n")

	if strings.Contains(updated, v2OrchestrionImport) {
		if updated == text {
			return nil
		}
		if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
			return fmt.Errorf("write orchestrion.tool.go: %w", err)
		}
		return nil
	}

	baseOrchestrionPattern := `(?m)^(\s*_\s*"github\.com/DataDog/orchestrion"(?:\s*//.*)?\s*)$`
	if re := regexp.MustCompile(baseOrchestrionPattern); re.MatchString(updated) {
		updated = re.ReplaceAllString(updated, `${1}`+"\n\t"+v2OrchestrionImport)
	} else if strings.Contains(updated, ")\n") {
		updated = strings.Replace(updated, ")\n", "\t"+v2OrchestrionImport+"\n)\n", 1)
	} else {
		return fmt.Errorf("patch orchestrion.tool.go: could not locate import block")
	}

	if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
		return fmt.Errorf("write orchestrion.tool.go: %w", err)
	}
	return nil
}

func warmOrchestrionModuleCache(cfg config) error {
	commands := [][]string{
		{"mod", "download", "github.com/DataDog/dd-trace-go/v2"},
		{"list", "-mod=mod", "github.com/DataDog/dd-trace-go/v2/ddtrace/tracer"},
		{"list", "-mod=mod", "github.com/DataDog/dd-trace-go/v2/profiler"},
		{"list", "-mod=mod", "github.com/DataDog/dd-trace-go/v2/instrumentation/env"},
	}

	for _, args := range commands {
		cmd := exec.Command("go", args...)
		cmd.Dir = cfg.goModuleDir
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		cmd.Env = orchestrionBootstrapEnv()
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("run `go %s` in %s: %w", strings.Join(args, " "), cfg.goModuleDir, err)
		}
	}

	return nil
}

func orchestrionBootstrapEnv() []string {
	env := append([]string{}, os.Environ()...)
	cacheRoot := filepath.Join(os.TempDir(), sharedOrchestrionCacheDirName)
	goModCache := filepath.Join(cacheRoot, "pkg", "mod")
	goBuildCache := filepath.Join(cacheRoot, "cache")

	env = append(env,
		"GO111MODULE=on",
		"GOPATH="+cacheRoot,
		"GOMODCACHE="+goModCache,
		"GOCACHE="+goBuildCache,
		"GOPROXY=https://proxy.golang.org,direct",
		"GOSUMDB=sum.golang.org",
	)
	return env
}

func writeStarterOrchestrionYML(cfg config) error {
	path := filepath.Join(cfg.goModuleDir, "orchestrion.yml")
	if _, err := os.Stat(path); err == nil && !cfg.force {
		return nil
	} else if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("stat orchestrion.yml: %w", err)
	}
	if err := os.WriteFile(path, []byte(defaultStarterOrchestrionYML), 0o644); err != nil {
		return fmt.Errorf("write orchestrion.yml: %w", err)
	}
	return nil
}
