# Unless explicitly stated otherwise all files in this repository are licensed under
# the Apache 2.0 License.
#
# This product includes software developed at Datadog
# (https://www.datadoghq.com/) Copyright 2025-Present Datadog, Inc.

"""Integrated Go-focused module extension for Test Optimization data."""

load(
    "@datadog-rules-test-optimization//tools/core:common_utils.bzl",
    "dedup_keys",
    "fail_with_prefix",
    "sanitize_label_fragment",
)
load(
    "@datadog-rules-test-optimization//tools/core:test_optimization_multi_sync.bzl",
    "test_optimization_multi_aggregate",
)
load(
    "@datadog-rules-test-optimization//tools/core:test_optimization_sync.bzl",
    "HTTP_POLICY_ATTR_UNSET",
    "test_optimization_sync",
)

def _compute_service_keys(services):
    raw_keys = []
    for service in services:
        raw_keys.append(sanitize_label_fragment(service))
    return dedup_keys(raw_keys)

def _compute_repo_names(base_name, service_keys):
    repo_names = []
    for key in service_keys:
        repo_names.append("%s_%s" % (base_name, key))
    return repo_names

def _record_repo_owner_or_fail(seen_repo_owners, repo_name, owner, tag_name):
    prev_owner = seen_repo_owners.get(repo_name)
    if prev_owner != None:
        fail_with_prefix(
            "test_optimization_go",
            "duplicate repository name '%s' generated by modules '%s' and '%s'. Use unique `name` values across %s tags." %
            (repo_name, prev_owner, owner, tag_name),
        )
    seen_repo_owners[repo_name] = owner

def _build_go_single_repo_spec(
        name,
        service,
        module_path = "",
        runtime_version = "",
        runtime_arch = "",
        out_dir = "",
        http_connect_timeout_seconds = HTTP_POLICY_ATTR_UNSET,
        http_max_time_seconds = HTTP_POLICY_ATTR_UNSET,
        http_retry_attempts = HTTP_POLICY_ATTR_UNSET,
        http_retry_delay_seconds = HTTP_POLICY_ATTR_UNSET,
        http_execute_timeout_buffer_seconds = HTTP_POLICY_ATTR_UNSET,
        known_tests = True,
        test_management = True,
        flaky_tests = True,
        enabled = True,
        enabled_by_env = True,
        require_git_metadata = False,
        debug = False):
    """Build the complete sync spec for one Go service repository."""
    return {
        "name": name,
        "repo_name": name,
        "out_dir": out_dir,
        "service": service,
        "runtime_name": "go",
        "runtime_version": runtime_version,
        "runtime_arch": runtime_arch,
        "runtime_module_path": module_path,
        "http_connect_timeout_seconds": http_connect_timeout_seconds,
        "http_max_time_seconds": http_max_time_seconds,
        "http_retry_attempts": http_retry_attempts,
        "http_retry_delay_seconds": http_retry_delay_seconds,
        "http_execute_timeout_buffer_seconds": http_execute_timeout_buffer_seconds,
        "known_tests": known_tests,
        "test_management": test_management,
        "flaky_tests": flaky_tests,
        "enabled": enabled,
        "enabled_by_env": enabled_by_env,
        "require_git_metadata": require_git_metadata,
        "debug": debug,
    }

def _build_go_multi_repo_specs(
        name,
        services,
        module_path = "",
        runtime_version = "",
        runtime_arch = "",
        out_dir = "",
        http_connect_timeout_seconds = HTTP_POLICY_ATTR_UNSET,
        http_max_time_seconds = HTTP_POLICY_ATTR_UNSET,
        http_retry_attempts = HTTP_POLICY_ATTR_UNSET,
        http_retry_delay_seconds = HTTP_POLICY_ATTR_UNSET,
        http_execute_timeout_buffer_seconds = HTTP_POLICY_ATTR_UNSET,
        known_tests = True,
        test_management = True,
        flaky_tests = True,
        enabled = True,
        enabled_by_env = True,
        require_git_metadata = False,
        debug = False):
    """Build the per-service sync specs for a multi-service Go tag."""
    service_keys = _compute_service_keys(services)
    repo_names = _compute_repo_names(name, service_keys)
    specs = []
    for i in range(len(services)):
        specs.append(_build_go_single_repo_spec(
            name = repo_names[i],
            service = services[i],
            module_path = module_path,
            runtime_version = runtime_version,
            runtime_arch = runtime_arch,
            out_dir = out_dir,
            http_connect_timeout_seconds = http_connect_timeout_seconds,
            http_max_time_seconds = http_max_time_seconds,
            http_retry_attempts = http_retry_attempts,
            http_retry_delay_seconds = http_retry_delay_seconds,
            http_execute_timeout_buffer_seconds = http_execute_timeout_buffer_seconds,
            known_tests = known_tests,
            test_management = test_management,
            flaky_tests = flaky_tests,
            enabled = enabled,
            enabled_by_env = enabled_by_env,
            require_git_metadata = require_git_metadata,
            debug = debug,
        ))
    return specs

build_go_single_repo_spec_for_tests = _build_go_single_repo_spec
build_go_multi_repo_specs_for_tests = _build_go_multi_repo_specs

def _materialize_single_service_repo(call):
    test_optimization_sync(**_build_go_single_repo_spec(
        name = call.name,
        service = call.service,
        module_path = call.module_path,
        runtime_version = call.runtime_version,
        runtime_arch = call.runtime_arch,
        out_dir = call.out_dir,
        http_connect_timeout_seconds = call.http_connect_timeout_seconds,
        http_max_time_seconds = call.http_max_time_seconds,
        http_retry_attempts = call.http_retry_attempts,
        http_retry_delay_seconds = call.http_retry_delay_seconds,
        http_execute_timeout_buffer_seconds = call.http_execute_timeout_buffer_seconds,
        known_tests = call.known_tests,
        test_management = call.test_management,
        flaky_tests = call.flaky_tests,
        enabled = call.enabled,
        enabled_by_env = call.enabled_by_env,
        require_git_metadata = call.require_git_metadata,
        debug = call.debug,
    ))

def _materialize_multi_service_repos(call):
    service_keys = _compute_service_keys(call.services)
    repo_names = _compute_repo_names(call.name, service_keys)

    for spec in _build_go_multi_repo_specs(
        name = call.name,
        services = call.services,
        module_path = call.module_path,
        runtime_version = call.runtime_version,
        runtime_arch = call.runtime_arch,
        out_dir = call.out_dir,
        http_connect_timeout_seconds = call.http_connect_timeout_seconds,
        http_max_time_seconds = call.http_max_time_seconds,
        http_retry_attempts = call.http_retry_attempts,
        http_retry_delay_seconds = call.http_retry_delay_seconds,
        http_execute_timeout_buffer_seconds = call.http_execute_timeout_buffer_seconds,
        known_tests = call.known_tests,
        test_management = call.test_management,
        flaky_tests = call.flaky_tests,
        enabled = call.enabled,
        enabled_by_env = call.enabled_by_env,
        require_git_metadata = call.require_git_metadata,
        debug = call.debug,
    ):
        test_optimization_sync(**spec)

    test_optimization_multi_aggregate(
        name = call.name,
        service_keys = service_keys,
        repo_names = repo_names,
        debug = call.debug,
    )

def _test_optimization_go_extension_impl(module_ctx):
    """Create synced Test Optimization repos for Go services."""
    seen_repo_owners = {}

    for mod in module_ctx.modules:
        owner = mod.name or "<unnamed-module>"
        for call in mod.tags.test_optimization_go:
            services = list(call.services or [])
            if call.service and services:
                fail_with_prefix("test_optimization_go", "set either `service` or `services`, not both")
            if not call.service and not services:
                fail_with_prefix("test_optimization_go", "one of `service` or `services` must be set")

            if services:
                service_keys = _compute_service_keys(services)
                for repo_name in [call.name] + _compute_repo_names(call.name, service_keys):
                    _record_repo_owner_or_fail(seen_repo_owners, repo_name, owner, "test_optimization_go")
                _materialize_multi_service_repos(call)
            else:
                _record_repo_owner_or_fail(seen_repo_owners, call.name, owner, "test_optimization_go")
                _materialize_single_service_repo(call)

test_optimization_go_extension = module_extension(
    implementation = _test_optimization_go_extension_impl,
    tag_classes = {
        "test_optimization_go": tag_class(attrs = {
            "name": attr.string(mandatory = True),
            "out_dir": attr.string(),
            "service": attr.string(),
            "services": attr.string_list(),
            "runtime_version": attr.string(),
            "runtime_arch": attr.string(),
            "module_path": attr.string(),
            "http_connect_timeout_seconds": attr.int(default = HTTP_POLICY_ATTR_UNSET),
            "http_max_time_seconds": attr.int(default = HTTP_POLICY_ATTR_UNSET),
            "http_retry_attempts": attr.int(default = HTTP_POLICY_ATTR_UNSET),
            "http_retry_delay_seconds": attr.int(default = HTTP_POLICY_ATTR_UNSET),
            "http_execute_timeout_buffer_seconds": attr.int(default = HTTP_POLICY_ATTR_UNSET),
            "known_tests": attr.bool(default = True),
            "test_management": attr.bool(default = True),
            "flaky_tests": attr.bool(default = True),
            "enabled": attr.bool(default = True),
            "enabled_by_env": attr.bool(default = True),
            "require_git_metadata": attr.bool(default = False),
            "debug": attr.bool(default = False),
        }),
    },
)
