# Generated by tools/dev/generate_rules_go_fork_maps.py. Do not edit by hand.

RULES_GO_DEFAULT_UPSTREAM = "v0_60_0"
RULES_GO_DEFAULT_VARIANT = "base"
RULES_GO_FORKS = {
    "v0_60_0": {
        "base": "third_party/rgo/v0_60_0/base",
    },
    "v0_61_1": {
        "base": "third_party/rgo/v0_61_1/base",
    },
    "v0_62_0": {
        "base": "third_party/rgo/v0_62_0/base",
    },
}

def rules_go_fork_strip_prefix(upstream, variant):
    effective_upstream = upstream or RULES_GO_DEFAULT_UPSTREAM
    if effective_upstream == "default":
        effective_upstream = RULES_GO_DEFAULT_UPSTREAM
    effective_variant = variant or RULES_GO_DEFAULT_VARIANT
    if effective_variant == "default":
        effective_variant = RULES_GO_DEFAULT_VARIANT
    if effective_variant == "complete":
        fail("rules_go_variant \"complete\" is no longer supported. Use \"base\".")
    if effective_upstream not in RULES_GO_FORKS:
        fail("rules_go_upstream must be one of %s, got %r" % (sorted(RULES_GO_FORKS.keys()), effective_upstream))
    variants = RULES_GO_FORKS[effective_upstream]
    if effective_variant not in variants:
        fail("rules_go_variant must be one of %s for rules_go_upstream %r, got %r" % (sorted(variants.keys()), effective_upstream, variant))
    return variants[effective_variant]
