# Unless explicitly stated otherwise all files in this repository are licensed under
# the Apache 2.0 License.
#
# This product includes software developed at Datadog
# (https://www.datadoghq.com/) Copyright 2025-Present Datadog, Inc.

blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://github.com/DataDog/rules_test_optimization/security/advisories/new
    about: Please report security vulnerabilities privately.
