// Code generated by tools/dev/generate_rules_go_fork_maps.py; DO NOT EDIT.

package onboardingpins

const DefaultRulesGoUpstream = "v0_60_0"

var rulesGoForkStripPrefixes = map[string]map[string]string{
	"v0_60_0": {
		"base": "third_party/rgo/v0_60_0/base",
	},
	"v0_61_1": {
		"base": "third_party/rgo/v0_61_1/base",
	},
}
