#!/usr/bin/env python3
# Unless explicitly stated otherwise all files in this repository are licensed under
# the Apache 2.0 License.
#
# This product includes software developed at Datadog
# (https://www.datadoghq.com/) Copyright 2025-Present Datadog, Inc.

"""Generate Starlark and Go fork-selection maps from the rules_go fork registry."""

from __future__ import annotations

import argparse
from pathlib import Path
import shutil
import subprocess
import sys

try:
    from tools.dev.rules_go_fork_registry import DEFAULT_REGISTRY, REPO_ROOT, load_registry
except ModuleNotFoundError:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from tools.dev.rules_go_fork_registry import DEFAULT_REGISTRY, REPO_ROOT, load_registry


STARLARK_OUT = REPO_ROOT / "tools" / "go" / "rules_go_forks.bzl"
GO_OUT = REPO_ROOT / "modules" / "go" / "tools" / "onboardingpins" / "rules_go_forks_gen.go"


def repo_rel(path: Path) -> str:
    """Return a repository-relative POSIX path for generated content."""
    return path.relative_to(REPO_ROOT).as_posix()


def render_starlark() -> str:
    """Render the generated Starlark fork map."""
    registry = load_registry(DEFAULT_REGISTRY)
    lines = [
        "# Generated by tools/dev/generate_rules_go_fork_maps.py. Do not edit by hand.",
        "",
        'RULES_GO_DEFAULT_UPSTREAM = "%s"' % registry.default_upstream,
        'RULES_GO_DEFAULT_VARIANT = "%s"' % registry.default_variant,
        "RULES_GO_FORKS = {",
    ]
    selections = registry.selections()
    for upstream_id in registry.upstream_ids():
        lines.append('    "%s": {' % upstream_id)
        for selection in selections:
            if selection.upstream_id == upstream_id:
                lines.append('        "%s": "%s",' % (selection.variant, repo_rel(selection.tree_path)))
        lines.append("    },")
    lines.extend(
        [
            "}",
            "",
            "def rules_go_fork_strip_prefix(upstream, variant):",
            "    effective_upstream = upstream or RULES_GO_DEFAULT_UPSTREAM",
            '    if effective_upstream == "default":',
            "        effective_upstream = RULES_GO_DEFAULT_UPSTREAM",
            "    effective_variant = variant or RULES_GO_DEFAULT_VARIANT",
            '    if effective_variant == "default":',
            "        effective_variant = RULES_GO_DEFAULT_VARIANT",
            '    if effective_variant == "complete":',
            '        fail("rules_go_variant \\"complete\\" is no longer supported. Use \\"base\\".")',
            "    if effective_upstream not in RULES_GO_FORKS:",
            '        fail("rules_go_upstream must be one of %s, got %r" % (sorted(RULES_GO_FORKS.keys()), effective_upstream))',
            "    variants = RULES_GO_FORKS[effective_upstream]",
            "    if effective_variant not in variants:",
            '        fail("rules_go_variant must be one of %s for rules_go_upstream %r, got %r" % (sorted(variants.keys()), effective_upstream, variant))',
            "    return variants[effective_variant]",
            "",
        ]
    )
    return "\n".join(lines)


def render_go() -> str:
    """Render the generated Go fork map."""
    registry = load_registry(DEFAULT_REGISTRY)
    lines = [
        "// Code generated by tools/dev/generate_rules_go_fork_maps.py; DO NOT EDIT.",
        "",
        "package onboardingpins",
        "",
        'const DefaultRulesGoUpstream = "%s"' % registry.default_upstream,
        "",
        "var rulesGoForkStripPrefixes = map[string]map[string]string{",
    ]
    selections = registry.selections()
    for upstream_id in registry.upstream_ids():
        lines.append('\t"%s": {' % upstream_id)
        for selection in selections:
            if selection.upstream_id == upstream_id:
                lines.append('\t\t"%s": "%s",' % (selection.variant, repo_rel(selection.tree_path)))
        lines.append("\t},")
    lines.extend(["}", ""])
    return gofmt("\n".join(lines))


def gofmt(content: str) -> str:
    """Format generated Go source."""
    if shutil.which("gofmt") is None:
        raise RuntimeError(
            "gofmt is required to generate rules_go_forks_gen.go; install Go or ensure gofmt is on PATH"
        )
    result = subprocess.run(
        ["gofmt"],
        input=content,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr)
    return result.stdout


def write_if_changed(path: Path, content: str) -> bool:
    """Write content when it differs from the current file."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    """Parse CLI arguments and generate or check fork map files."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale.")
    parser.add_argument("--print-upstreams", action="store_true", help="Print supported upstream ids from the registry.")
    args = parser.parse_args(argv)

    if args.print_upstreams:
        registry = load_registry(DEFAULT_REGISTRY)
        for upstream_id in registry.upstream_ids():
            print(upstream_id)
        return 0

    outputs = {
        STARLARK_OUT: render_starlark(),
        GO_OUT: render_go(),
    }
    stale: list[str] = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(REPO_ROOT).as_posix())
        else:
            write_if_changed(path, content)

    if stale:
        print("stale generated rules_go fork map files:", file=sys.stderr)
        for path in stale:
            print(path, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
