#!/usr/bin/env bash
set -euo pipefail

# Run the fast vendored rules_go checks from a selected published variant tree.
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
tmp_root="$(mktemp -d "${TMPDIR:-/tmp}/rules_go_variant_smoke.XXXXXX")"
vendor_root="${tmp_root}/rules_go_orchestrion"
empty_orchestrion_tool_repo="${tmp_root}/rules_go_orchestrion_tool_empty"
RULES_GO_VARIANT="${RULES_GO_VARIANT:-complete}"
BAZEL_VERSION="${BAZEL_VERSION:-$(tr -d '[:space:]' < "${repo_root}/.bazelversion")}"
BAZEL_JOBS="${BAZEL_JOBS:-1}"
BAZEL_EXTRA_ARGS=()
if [[ -n "${BAZEL_DISTDIR:-}" ]]; then
  BAZEL_EXTRA_ARGS+=(--distdir="${BAZEL_DISTDIR}")
fi
host_os="$(uname -s)"
host_arch="$(uname -m)"

cleanup() {
  rm -rf "${tmp_root}"
}
trap cleanup EXIT INT TERM HUP

case "${RULES_GO_VARIANT}" in
  base|complete)
    ;;
  *)
    echo "error: RULES_GO_VARIANT must be 'base' or 'complete', got '${RULES_GO_VARIANT}'" >&2
    exit 1
    ;;
esac

python3 "${repo_root}/tools/dev/verify_rules_go_variants.py"
mkdir -p "${vendor_root}"
cp -R "${repo_root}/third_party/rules_go_orchestrion_${RULES_GO_VARIANT}/." "${vendor_root}/"
cp -R "${repo_root}/tools/tests/rules_go_variant_regressions/." "${vendor_root}/"

augment_vendor_module() {
  local module_file="${vendor_root}/MODULE.bazel"

  # The clean base keeps the recorded base MODULE unchanged, but the vendored
  # buildinfo regression targets still need org_golang_x_sys exported from the
  # go_deps extension. Inject it only in the temp maintainer tree so the
  # checked-in clean base remains identical to the recorded base commit.
  python3 - "${module_file}" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
needle = '    "org_golang_x_net",\n'
if '"org_golang_x_sys",' in text:
    raise SystemExit(0)
if needle not in text:
    raise SystemExit(f"missing go_deps use_repo anchor in {path}")
path.write_text(
    text.replace(needle, needle + '    "org_golang_x_sys",\n', 1),
    encoding="utf-8",
)
PY
}

augment_vendor_module

create_empty_orchestrion_tool_repo() {
  mkdir -p "${empty_orchestrion_tool_repo}"
  cat > "${empty_orchestrion_tool_repo}/WORKSPACE" <<'EOF'
workspace(name = "rules_go_orchestrion_tool")
EOF
  cat > "${empty_orchestrion_tool_repo}/MODULE.bazel" <<'EOF'
module(name = "rules_go_orchestrion_tool")
EOF
  : > "${empty_orchestrion_tool_repo}/REPO.bazel"
  cat > "${empty_orchestrion_tool_repo}/BUILD.bazel" <<'EOF'
# Generated by the smoke harness for rules_go self-tests that exercise
# non-instrumented WORKSPACE mode without configuring the Orchestrion tool.
filegroup(
    name = "orchestrion",
    srcs = [],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "dd_trace_go_version_file",
    srcs = [],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "dd_trace_go_module_proxy_files",
    srcs = [],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "dd_trace_go_module_proxy_root_marker",
    srcs = [],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "orchestrion_tool_version_file",
    srcs = [],
    visibility = ["//visibility:public"],
)
EOF
}

create_empty_orchestrion_tool_repo

run_vendor() {
  (
    cd "${vendor_root}"
    # Keep the smoke lane independent from host-injected private Go proxy
    # settings so the materialized vendor tree resolves public modules the same
    # way on maintainer laptops and in CI.
    GOPROXY="https://proxy.golang.org,direct" \
    GOSUMDB="sum.golang.org" \
    GOPRIVATE="" \
    GONOPROXY="" \
    GONOSUMDB="" \
    GIT_TERMINAL_PROMPT="0" \
    USE_BAZEL_VERSION="${BAZEL_VERSION}" "$@"
  )
}

bazel_test() {
  run_vendor bazelisk test --jobs="${BAZEL_JOBS}" "${BAZEL_EXTRA_ARGS[@]}" "$@"
}

bazel_build() {
  run_vendor bazelisk build --jobs="${BAZEL_JOBS}" "${BAZEL_EXTRA_ARGS[@]}" "$@"
}

if [[ "${RULES_GO_VARIANT}" == "base" ]]; then
  run_vendor env GOWORK=off go test ./go/tools/bzltestutil -count=1
else
  echo "Skipping go/tools/bzltestutil upstream unit tests for complete; the complete compatibility layer intentionally changes XML log emission semantics without carrying upstream test rewrites." >&2
fi
# Keep the Starlark smoke lane focused on the variant-sensitive suites instead of
# the whole package. The broader package pulls in unrelated SDK/provider tests
# that do not prove the variant split and are less stable across hosts.
bazel_test \
  //tests/core/starlark:context_tests_test_0
if [[ "${host_os}" == "Darwin" ]]; then
  bazel_test \
    //tests/core/cross:go_cross_binary_test \
    //tests/legacy/providers:source_test
  echo "Skipping //tests/core/cross:proto_test, //tests/legacy/info:info, and //tests/core/nogo/custom:custom_test on ${host_os}/${host_arch}; those maintainer proof targets are currently not stable on the local macOS host." >&2
else
  nested_workspace_flags="--enable_workspace --override_repository=rules_go_orchestrion_tool=${empty_orchestrion_tool_repo}"

  # proto_test starts a nested Bazel invocation that may build protobuf from
  # source on fresh Linux runners, so give that smoke lane enough time without
  # weakening the surrounding job timeout.
  bazel_test \
    --test_timeout=900 \
    //tests/core/cross:go_cross_binary_test \
    //tests/core/cross:proto_test \
    //tests/legacy/info:info \
    //tests/legacy/providers:source_test
  # custom_test creates WORKSPACE-style nested Bazel workspaces through
  # go/tools/bazel_testing. Bazel 8 requires WORKSPACE mode to be enabled
  # explicitly in those recursive invocations.
  bazel_test \
    --test_env="GO_BAZEL_TEST_BAZELFLAGS=${nested_workspace_flags}" \
    //tests/core/nogo/custom:custom_test
fi
bazel_test //tests/core/c_linkmodes:c-archive_test //tests/core/c_linkmodes:c-shared_test
bazel_build //tests/core/c_linkmodes:go_with_cgo_dep_caller
if [[ "${RULES_GO_VARIANT}" == "complete" && "${host_os}" == "Linux" && "${host_arch}" == "x86_64" ]]; then
  bazel_test //tests/core/cgo/asm_cflags:asm_cflags_test
elif [[ "${RULES_GO_VARIANT}" != "complete" ]]; then
  echo "Skipping //tests/core/cgo/asm_cflags:asm_cflags_test for ${RULES_GO_VARIANT}; the asm cflags compatibility target belongs to the complete variant." >&2
else
  echo "Skipping //tests/core/cgo/asm_cflags:asm_cflags_test on ${host_os}/${host_arch}; the regression target is Linux x86_64 only." >&2
fi
