#!/usr/bin/env bash
set -euo pipefail

# Run the fast vendored rules_go patch checks from a materialized patched tree
# so the clean base fork stays separate from the optional patch bundle.
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
tmp_root="$(mktemp -d "${TMPDIR:-/tmp}/rules_go_patch_smoke.XXXXXX")"
vendor_root="${tmp_root}/rules_go_orchestrion"
empty_orchestrion_tool_repo="${tmp_root}/rules_go_orchestrion_tool_empty"
BAZEL_VERSION="${BAZEL_VERSION:-$(tr -d '[:space:]' < "${repo_root}/.bazelversion")}"
host_os="$(uname -s)"
host_arch="$(uname -m)"

cleanup() {
  rm -rf "${tmp_root}"
}
trap cleanup EXIT INT TERM HUP

python3 "${repo_root}/tools/dev/verify_rules_go_patch_series.py" --bundle all_patches
python3 "${repo_root}/tools/dev/materialize_rules_go_patch_tree.py" \
  --bundle all_patches \
  --destination "${vendor_root}" \
  --apply-proof-overlay

patch_vendor_module() {
  local module_file="${vendor_root}/MODULE.bazel"

  # The clean base keeps the recorded base MODULE unchanged, but the vendored
  # buildinfo regression targets still need org_golang_x_sys exported from the
  # go_deps extension. Inject it only in the temp maintainer tree so the
  # checked-in clean base remains identical to the recorded base commit.
  python3 - "${module_file}" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
needle = '    "org_golang_x_net",\n'
if '"org_golang_x_sys",' in text:
    raise SystemExit(0)
if needle not in text:
    raise SystemExit(f"missing go_deps use_repo anchor in {path}")
path.write_text(
    text.replace(needle, needle + '    "org_golang_x_sys",\n', 1),
    encoding="utf-8",
)
PY
}

patch_vendor_module

create_empty_orchestrion_tool_repo() {
  mkdir -p "${empty_orchestrion_tool_repo}"
  cat > "${empty_orchestrion_tool_repo}/WORKSPACE" <<'EOF'
workspace(name = "rules_go_orchestrion_tool")
EOF
  cat > "${empty_orchestrion_tool_repo}/MODULE.bazel" <<'EOF'
module(name = "rules_go_orchestrion_tool")
EOF
  : > "${empty_orchestrion_tool_repo}/REPO.bazel"
  cat > "${empty_orchestrion_tool_repo}/BUILD.bazel" <<'EOF'
# Generated by the smoke harness for rules_go self-tests that exercise
# non-instrumented WORKSPACE mode without configuring the Orchestrion tool.
filegroup(
    name = "orchestrion",
    srcs = [],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "dd_trace_go_version_file",
    srcs = [],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "dd_trace_go_module_proxy_files",
    srcs = [],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "dd_trace_go_module_proxy_root_marker",
    srcs = [],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "orchestrion_tool_version_file",
    srcs = [],
    visibility = ["//visibility:public"],
)
EOF
}

create_empty_orchestrion_tool_repo

run_vendor() {
  (
    cd "${vendor_root}"
    # Keep the smoke lane independent from host-injected private Go proxy
    # settings so the materialized vendor tree resolves public modules the same
    # way on maintainer laptops and in CI.
    GOPROXY="https://proxy.golang.org,direct" \
    GOSUMDB="sum.golang.org" \
    GOPRIVATE="" \
    GONOPROXY="" \
    GONOSUMDB="" \
    GIT_TERMINAL_PROMPT="0" \
    USE_BAZEL_VERSION="${BAZEL_VERSION}" "$@"
  )
}

run_vendor env GOWORK=off go test ./go/tools/bzltestutil -count=1
run_vendor bazelisk test //go/tools/builders:buildinfo_test
# Keep the buildinfo smoke lane on the stable metadata regressions that the
# patch split is expected to preserve directly. The broader suite's external
# dependency version check still depends on vendored self-test module plumbing
# that is outside the clean-base versus optional-bundle split itself.
run_vendor bazelisk test \
  //tests/core/buildinfo:metadata_test \
  //tests/core/buildinfo:srcs_only_test
# Keep the Starlark smoke lane focused on the patch-sensitive suites instead of
# the whole package. The broader package pulls in unrelated SDK/provider tests
# that do not prove the optional patch split and are less stable across hosts.
run_vendor bazelisk test \
  //tests/core/starlark:context_tests_test_0 \
  //tests/core/starlark:context_tests_test_1 \
  //tests/core/starlark:link_tests_test_0 \
  //tests/core/starlark:link_tests_test_1
if [[ "${host_os}" == "Darwin" ]]; then
  run_vendor bazelisk test \
    //tests/core/cross:go_cross_binary_test \
    //tests/legacy/providers:source_test
  echo "Skipping //tests/core/cross:proto_test, //tests/legacy/info:info, and //tests/core/nogo/custom:custom_test on ${host_os}/${host_arch}; those maintainer proof targets are currently not stable on the local macOS host." >&2
else
  nested_workspace_flags="--enable_workspace --override_repository=rules_go_orchestrion_tool=${empty_orchestrion_tool_repo}"

  # proto_test starts a nested Bazel invocation that may build protobuf from
  # source on fresh Linux runners, so give that smoke lane enough time without
  # weakening the surrounding job timeout.
  run_vendor bazelisk test \
    --test_timeout=900 \
    //tests/core/cross:go_cross_binary_test \
    //tests/core/cross:proto_test \
    //tests/legacy/info:info \
    //tests/legacy/providers:source_test
  # custom_test creates WORKSPACE-style nested Bazel workspaces through
  # go/tools/bazel_testing. Bazel 8 requires WORKSPACE mode to be enabled
  # explicitly in those recursive invocations.
  run_vendor bazelisk test \
    --test_env="GO_BAZEL_TEST_BAZELFLAGS=${nested_workspace_flags}" \
    //tests/core/nogo/custom:custom_test
fi
run_vendor bazelisk test //tests/core/c_linkmodes:c-archive_test //tests/core/c_linkmodes:c-shared_test
run_vendor bazelisk build //tests/core/c_linkmodes:go_with_cgo_dep_caller
run_vendor bazelisk build //tests/core/cgo:embed_chain_bin
if [[ "${host_os}" == "Linux" && "${host_arch}" == "x86_64" ]]; then
  run_vendor bazelisk test //tests/core/cgo/asm_cflags:asm_cflags_test
else
  echo "Skipping //tests/core/cgo/asm_cflags:asm_cflags_test on ${host_os}/${host_arch}; the regression target is Linux x86_64 only." >&2
fi
