# BUILD file to make this directory a Bazel package
# This allows the test_optimization_sync.bzl file to be referenced from other modules

exports_files(["test_optimization_sync.bzl", "test_optimization_uploader_test.bzl", "topt_go_test.bzl"])
