# BUILD file to make this directory a Bazel package
# This allows the test_optimization_sync.bzl file to be referenced from other modules

exports_files([
    "common_utils.bzl",
    "schemas/agentless-schema.json",
    "test_optimization_sync.bzl",
    "test_optimization_multi_sync.bzl",
    "test_optimization_uploader.bzl",
    "validate_payload_schema.py",
    "topt_go_test.bzl",
    "topt_go_infer.bzl",
])
