"""Multi-service Datadog Test Optimization module extension.

Provides a higher-level module extension that instantiates the existing
`test_optimization_sync` repository rule once per service, and also creates
an aggregator repository that exposes service-suffixed labels so consumers
can select a single service's data.

Why this exists:
- Monorepos frequently map multiple logical services to one Bazel workspace.
- The single-service extension is intentionally simple; this layer composes it
  without changing the underlying repository rule contracts.

How it works:
1) For each requested service, instantiate `test_optimization_sync` with a
   generated repository name (`<name>_<sanitized_service>`).
2) Generate an aggregator repository (`name`) that:
   - re-exports a `topt_data_by_service` mapping in `export.bzl`,
   - publishes service-qualified filegroups:
     `:test_optimization_files_<service>`,
     `:test_optimization_context_<service>`,
     `:module_<service>_<module_label>`.

Maintenance notes:
- Service keys are sanitized and de-duplicated via `dedup_keys`; this means
  user-provided service names can map to suffixed keys (`foo`, `foo_2`).
- Keep generated label naming stable; these labels are consumed directly in
  downstream BUILD files.
"""

load("//tools:test_optimization_sync.bzl", "test_optimization_sync")
load(
    "//tools:common_utils.bzl",
    "dedup_keys",
    "sanitize_label_fragment",
)

def _compute_service_keys(services):
    raw_keys = []
    for service in services:
        raw_keys.append(sanitize_label_fragment(service))
    return dedup_keys(raw_keys)

def _compute_repo_names(base_name, service_keys):
    repo_names = []
    for key in service_keys:
        repo_names.append("%s_%s" % (base_name, key))
    return repo_names

def _render_aggregate_bzl(service_keys, repo_names):
    if len(service_keys) != len(repo_names):
        fail("test_optimization_multi_aggregate: service_keys and repo_names length mismatch")

    # Build aggregate.bzl that loads each service's export and defines targets.
    lines = []
    lines.append("# Generated by test_optimization_multi_sync; aggregates per-service repos")

    # Load per-service exports with unique local symbols.
    for i in range(len(service_keys)):
        key = service_keys[i]
        repo = repo_names[i]
        sym = "svc_%s" % key
        lines.append('load("@%s//:export.bzl", %s = "topt_data")' % (repo, sym))
    lines.append("")

    # Re-export mapping for consumers.
    lines.append("topt_data_by_service = {")
    for i in range(len(service_keys)):
        key = service_keys[i]
        sym = "svc_%s" % key
        lines.append("  \"%s\": %s," % (key, sym))
    lines.append("}")
    lines.append("")

    # Macro that materializes aliased filegroups per service and module label.
    lines.append("def define_targets():")
    lines.append("  # Per-service top-level filegroups")
    for i in range(len(service_keys)):
        key = service_keys[i]
        repo = repo_names[i]
        lines.append("  native.filegroup(")
        lines.append("      name = \"test_optimization_files_%s\"," % key)
        lines.append("      srcs = [\"@%s//:test_optimization_files\"]," % repo)
        lines.append("      visibility = [\"//visibility:public\"],")
        lines.append("  )")
        lines.append("  native.filegroup(")
        lines.append("      name = \"test_optimization_context_%s\"," % key)
        lines.append("      srcs = [\"@%s//:test_optimization_context\"]," % repo)
        lines.append("      visibility = [\"//visibility:public\"],")
        lines.append("  )")
    lines.append("")
    lines.append("  # Per-module aliases per service (labels come from each service's export)")
    for i in range(len(service_keys)):
        key = service_keys[i]
        repo = repo_names[i]
        sym = "svc_%s" % key
        lines.append("  for _lab in %s[\"labels\"]:" % sym)
        lines.append("    native.filegroup(")
        lines.append("        name = \"module_%s_\" + _lab," % key)
        lines.append("        srcs = [\"@%s//:module_\" + _lab]," % repo)
        lines.append("        visibility = [\"//visibility:public\"],")
        lines.append("    )")
    return "\n".join(lines) + "\n"

# Public aliases for unit tests.
compute_multi_service_keys_for_tests = _compute_service_keys
compute_multi_repo_names_for_tests = _compute_repo_names
render_multi_aggregate_bzl_for_tests = _render_aggregate_bzl

# ---------------------------------------------------------------------------
# Aggregator repository rule
# ---------------------------------------------------------------------------

def _multi_aggregate_impl(ctx):
    # Build an in-repo Starlark shim (`aggregate.bzl`) rather than writing a
    # giant BUILD directly so generated logic remains easy to inspect/debug.
    keys = list(ctx.attr.service_keys)
    repos = list(ctx.attr.repo_names)
    ctx.file("aggregate.bzl", _render_aggregate_bzl(keys, repos))

    # Small export shim so consumers can load the mapping
    export_content = 'load(":aggregate.bzl", "topt_data_by_service")\n\n'
    ctx.file("export.bzl", export_content)

    build_content = (
        'load(":aggregate.bzl", "define_targets")\n' +
        "define_targets()\n\n" +
        'exports_files(["export.bzl"])\n'
    )
    ctx.file("BUILD", build_content)

test_optimization_multi_aggregate = repository_rule(
    implementation = _multi_aggregate_impl,
    attrs = {
        "service_keys": attr.string_list(mandatory = True),
        "repo_names": attr.string_list(mandatory = True),
        "debug": attr.bool(default = False),
    },
)

# ---------------------------------------------------------------------------
# Module extension
# ---------------------------------------------------------------------------

def _test_optimization_multi_sync_extension_impl(module_ctx):
    # Iterate tags and instantiate per-service repos + aggregator
    # This mirrors the single-service extension behavior while faning out
    # service-specific repositories in one declarative call.
    for mod in module_ctx.modules:
        for call in mod.tags.test_optimization_multi_sync:
            name = call.name
            services = list(call.services or [])
            if not services:
                fail("test_optimization_multi_sync: 'services' must be a non-empty list")

            # Compute deterministic service keys and per-service repo names.
            keys = _compute_service_keys(services)
            per_repo_names = _compute_repo_names(name, keys)
            for i in range(len(services)):
                svc = services[i]
                repo = per_repo_names[i]
                test_optimization_sync(
                    name = repo,
                    repo_name = repo,
                    out_dir = call.out_dir,  # optional; if set, used per-repo
                    service = svc,  # override/DD_SERVICE for this service
                    runtime_name = call.runtime_name,
                    runtime_version = call.runtime_version,
                    runtime_arch = call.runtime_arch,
                    known_tests = call.known_tests,
                    test_management = call.test_management,
                    debug = call.debug,
                )

            # Aggregator repository with service-suffixed labels
            test_optimization_multi_aggregate(
                name = name,
                service_keys = keys,
                repo_names = per_repo_names,
                debug = call.debug,
            )

test_optimization_multi_sync_extension = module_extension(
    implementation = _test_optimization_multi_sync_extension_impl,
    tag_classes = {
        "test_optimization_multi_sync": tag_class(attrs = {
            "name": attr.string(mandatory = True),
            "services": attr.string_list(mandatory = True),
            # Optional base output directory for fetched JSONs (applied per service repo)
            "out_dir": attr.string(),
            # Optional runtime.* overrides propagated to each per-service repo
            "runtime_name": attr.string(),
            "runtime_version": attr.string(),
            "runtime_arch": attr.string(),
            # Kill-switches propagated to each per-service repo
            "known_tests": attr.bool(default = True),
            "test_management": attr.bool(default = True),
            "debug": attr.bool(default = False),
        }),
    },
)
