# Multi-service Datadog Test Optimization module extension
#
# Provides a higher-level module extension that instantiates the existing
# `test_optimization_sync` repository rule once per service, and also creates
# an aggregator repository that exposes service-suffixed labels so consumers
# can select a single service's data.

load("//tools:test_optimization_sync.bzl", "test_optimization_sync")

# ---------------------------------------------------------------------------
# Helpers (local)
# ---------------------------------------------------------------------------

def _sanitize_label_fragment(name):
    s = (name or "").lower()
    allowed = "abcdefghijklmnopqrstuvwxyz0123456789_"
    out = []
    last_us = False
    for ch in s:
        if ch in allowed:
            out.append(ch)
            last_us = (ch == "_")
        elif not last_us:
            out.append("_")
            last_us = True

    # trim leading/trailing '_'
    # find first non-underscore
    n = len(out)
    start = 0
    found = False
    for i in range(n):
        if out[i] != "_":
            start = i
            found = True
            break
    if not found:
        return "service"
    end = start
    for k in range(n):
        j = n - 1 - k
        if j < 0:
            break
        if out[j] != "_":
            end = j + 1
            break
    frag = "".join(out[start:end])
    return frag or "service"

def _dedup_keys(keys):
    # Ensure sanitized keys are unique by appending numeric suffixes if needed
    seen = {}
    out = []
    for k in keys:
        c = seen.get(k, 0) + 1
        seen[k] = c
        out.append(k if c == 1 else ("%s_%d" % (k, c)))
    return out

# ---------------------------------------------------------------------------
# Aggregator repository rule
# ---------------------------------------------------------------------------

def _multi_aggregate_impl(ctx):
    debug = ctx.attr.debug

    keys = list(ctx.attr.service_keys)
    repos = list(ctx.attr.repo_names)
    if len(keys) != len(repos):
        fail("test_optimization_multi_aggregate: service_keys and repo_names length mismatch")

    # Build aggregate.bzl that loads each service's export and defines targets
    lines = []
    lines.append("# Generated by test_optimization_multi_sync; aggregates per-service repos")

    # Load per-service exports with unique local symbols
    for i in range(len(keys)):
        key = keys[i]
        repo = repos[i]
        sym = "svc_%s" % key
        lines.append('load("@%s//:export.bzl", %s = "topt_data")' % (repo, sym))
    lines.append("")

    # Re-export mapping for consumers
    lines.append("topt_data_by_service = {")
    for i in range(len(keys)):
        key = keys[i]
        sym = "svc_%s" % key
        lines.append("  \"%s\": %s," % (key, sym))
    lines.append("}")
    lines.append("")

    # Macro that materializes aliased filegroups per service and module label
    lines.append("def define_targets():")
    lines.append("  # Per-service top-level filegroups")
    for i in range(len(keys)):
        key = keys[i]
        repo = repos[i]
        lines.append("  native.filegroup(")
        lines.append("      name = \"test_optimization_files_%s\"," % key)
        lines.append("      srcs = [\"@%s//:test_optimization_files\"]," % repo)
        lines.append("      visibility = [\"//visibility:public\"],")
        lines.append("  )")
        lines.append("  native.filegroup(")
        lines.append("      name = \"test_optimization_context_%s\"," % key)
        lines.append("      srcs = [\"@%s//:test_optimization_context\"]," % repo)
        lines.append("      visibility = [\"//visibility:public\"],")
        lines.append("  )")
    lines.append("")
    lines.append("  # Per-module aliases per service (labels come from each service's export)")
    for i in range(len(keys)):
        key = keys[i]
        repo = repos[i]
        sym = "svc_%s" % key
        lines.append("  for _lab in %s[\"labels\"]:" % sym)
        lines.append("    native.filegroup(")
        lines.append("        name = \"module_%s_\" + _lab," % key)
        lines.append("        srcs = [\"@%s//:module_\" + _lab]," % repo)
        lines.append("        visibility = [\"//visibility:public\"],")
        lines.append("    )")

    ctx.file("aggregate.bzl", "\n".join(lines) + "\n")

    # Small export shim so consumers can load the mapping
    export_content = 'load(":aggregate.bzl", "topt_data_by_service")\n\n'
    ctx.file("export.bzl", export_content)

    build_content = (
        'load(":aggregate.bzl", "define_targets")\n' +
        "define_targets()\n\n" +
        'exports_files(["export.bzl"])\n'
    )
    ctx.file("BUILD", build_content)

test_optimization_multi_aggregate = repository_rule(
    implementation = _multi_aggregate_impl,
    attrs = {
        "service_keys": attr.string_list(mandatory = True),
        "repo_names": attr.string_list(mandatory = True),
        "debug": attr.bool(default = False),
    },
)

# ---------------------------------------------------------------------------
# Module extension
# ---------------------------------------------------------------------------

def _test_optimization_multi_sync_extension_impl(module_ctx):
    # Iterate tags and instantiate per-service repos + aggregator
    for mod in module_ctx.modules:
        for call in mod.tags.test_optimization_multi_sync:
            name = call.name
            services = list(call.services or [])
            if not services:
                fail("test_optimization_multi_sync: 'services' must be a non-empty list")

            # Compute sanitized keys and dedup
            raw_keys = [_sanitize_label_fragment(s) for s in services]
            keys = _dedup_keys(raw_keys)

            per_repo_names = []
            for i in range(len(services)):
                svc = services[i]
                key = keys[i]
                repo = "%s_%s" % (name, key)
                per_repo_names.append(repo)
                test_optimization_sync(
                    name = repo,
                    repo_name = repo,
                    out_dir = call.out_dir,  # optional; if set, used per-repo
                    service = svc,  # override/DD_SERVICE for this service
                    runtime_name = call.runtime_name,
                    runtime_version = call.runtime_version,
                    runtime_arch = call.runtime_arch,
                    known_tests = call.known_tests,
                    test_management = call.test_management,
                    debug = call.debug,
                )

            # Aggregator repository with service-suffixed labels
            test_optimization_multi_aggregate(
                name = name,
                service_keys = keys,
                repo_names = per_repo_names,
                debug = call.debug,
            )

test_optimization_multi_sync_extension = module_extension(
    implementation = _test_optimization_multi_sync_extension_impl,
    tag_classes = {
        "test_optimization_multi_sync": tag_class(attrs = {
            "name": attr.string(mandatory = True),
            "services": attr.string_list(mandatory = True),
            # Optional base output directory for fetched JSONs (applied per service repo)
            "out_dir": attr.string(),
            # Optional runtime.* overrides propagated to each per-service repo
            "runtime_name": attr.string(),
            "runtime_version": attr.string(),
            "runtime_arch": attr.string(),
            # Kill-switches propagated to each per-service repo
            "known_tests": attr.bool(default = True),
            "test_management": attr.bool(default = True),
            "debug": attr.bool(default = False),
        }),
    },
)
