# Unless explicitly stated otherwise all files in this repository are licensed under
# the Apache 2.0 License.
#
# This product includes software developed at Datadog
# (https://www.datadoghq.com/) Copyright 2025-Present Datadog, Inc.

load("@datadog-rules-test-optimization//tools/core:test_optimization_targets.bzl", "dd_test_optimization_targets")

# ONE doctor and ONE uploader target per workspace.
dd_test_optimization_targets(
    name = "test_optimization",
    context_data = [
        "@test_optimization_data_go//:test_optimization_context",
        "@test_optimization_data_python//:test_optimization_context",
        "@test_optimization_data_java//:test_optimization_context",
        "@test_optimization_data_nodejs//:test_optimization_context",
        "@test_optimization_data_dotnet//:test_optimization_context",
        "@test_optimization_data_ruby//:test_optimization_context",
    ],
)
