name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - "feature/**"

jobs:
  bazel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Bazel tests
        run: ./bazelw test //tools/...

      - name: Run mock server integration tests
        run: tools/tests/integration/run_mock_server_tests.sh
